/**
 * Created by gurihui on 2016/12/30.
 */
'use strict';

var gulp = require('gulp');
var Mock = require('mockjs');
var webserver = require('gulp-webserver');

//模拟数据
var data = {
    //手机号不存在
    "/api/priceList": {
        "success": true,
        "message": "",
        "results": [],
        "recordCount": 100
    }
};

gulp.task('mock', function () {
    gulp.src('market').pipe(webserver({
        host: 'localhost',
        port: 8000,
        middleware: function (req, res, next) {
            var arr = req.url.split('?');
            var pathname = arr[0];
            var queryArr = arr[1].split('&');
            var query = {};
            for (var i in queryArr) {
                var tArr = queryArr[i].split('=');
                if (tArr.length == 2 && !!tArr[1]) {
                    query[tArr[0]] = decodeURI(tArr[1]);
                }
            }
            console.log(query);
            var filtered = !!query ? price.filter(function (s) {
                return (!!!query.supplier || s.supplier.indexOf(query.supplier) > -1)
                    && (!!!query.coalQuality || s.coalQuality == query.coalQuality)
                    && (!!!query.coalType || s.coalType == query.coalType)
                    && (!!!query.beginDate || s.beginDate == query.beginDate)
                    && (!!!query.endDate || s.beginDate == query.endDate);
            }) : price;

            //if (params.sort.predicate) {
            //    filtered = filtered.sort(function (a, b) {
            //        return a[param.sort.predicate] - b[param.sort.predicate];
            //    });
            //}

            var result = filtered.slice(query.pageIndex, query.pageSize);

            data[pathname].results = result;

            res.end(JSON.stringify((data[pathname]) && Mock.mock(data[pathname])));
            next();
        }
    }));
});

var price = [
    {
        "id": 9516,
        "date": "2016-11-28T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 580.00,
        "priceEnum": 0
    }, {
        "id": 9517,
        "date": "2016-11-17T00:00:00",
        "supplier": "山西煤炭运销集团鸿泰煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "混煤",
        "priceType": "基准价格",
        "salesPrice": 350.00,
        "priceEnum": 0
    }, {
        "id": 9518,
        "date": "2016-11-15T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 580.00,
        "priceEnum": 0
    }, {
        "id": 9519,
        "date": "2016-11-15T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "筛末煤",
        "priceType": "基准价格",
        "salesPrice": 650.00,
        "priceEnum": 0
    }, {
        "id": 9520,
        "date": "2016-11-15T00:00:00",
        "supplier": "阳泉市上社煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 600.00,
        "priceEnum": 0
    }, {
        "id": 9521,
        "date": "2016-11-15T00:00:00",
        "supplier": "阳泉市上社煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "末煤",
        "priceType": "基准价格",
        "salesPrice": 570.00,
        "priceEnum": 0
    }, {
        "id": 9522,
        "date": "2016-11-15T00:00:00",
        "supplier": "阳泉市上社二景煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 580.00,
        "priceEnum": 0
    }, {
        "id": 9523,
        "date": "2016-11-15T00:00:00",
        "supplier": "阳泉市上社二景煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤2#",
        "priceType": "基准价格",
        "salesPrice": 460.00,
        "priceEnum": 0
    }, {
        "id": 9524,
        "date": "2016-11-15T00:00:00",
        "supplier": "山西煤炭运销集团阳泉二景和谐煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 470.00,
        "priceEnum": 0
    }, {
        "id": 9525,
        "date": "2016-11-15T00:00:00",
        "supplier": "山西煤炭运销集团盂县恒泰常顺煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤（常顺）",
        "priceType": "基准价格",
        "salesPrice": 540.00,
        "priceEnum": 0
    }, {
        "id": 9526,
        "date": "2016-11-15T00:00:00",
        "supplier": "山西煤炭运销集团盂县恒泰皇后煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 580.00,
        "priceEnum": 0
    }, {
        "id": 9527,
        "date": "2016-11-15T00:00:00",
        "supplier": "山西煤炭运销集团保安煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 590.00,
        "priceEnum": 0
    }, {
        "id": 9528,
        "date": "2016-11-15T00:00:00",
        "supplier": "山西煤炭运销集团保安煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "筛末煤",
        "priceType": "基准价格",
        "salesPrice": 650.00,
        "priceEnum": 0
    }, {
        "id": 9529,
        "date": "2016-11-15T00:00:00",
        "supplier": "山西煤炭运销集团旧街煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 530.00,
        "priceEnum": 0
    }, {
        "id": 9530,
        "date": "2016-11-15T00:00:00",
        "supplier": "山西煤炭运销集团鸿泰煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 650.00,
        "priceEnum": 0
    }, {
        "id": 9531,
        "date": "2016-11-14T00:00:00",
        "supplier": "山西煤炭运销集团阳泉上社晋玉煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 500.00,
        "priceEnum": 0
    }, {
        "id": 9532,
        "date": "2016-11-11T00:00:00",
        "supplier": "阳泉市上社煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 580.00,
        "priceEnum": 0
    }, {
        "id": 9533,
        "date": "2016-11-11T00:00:00",
        "supplier": "阳泉市上社二景煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 560.00,
        "priceEnum": 0
    }, {
        "id": 9534,
        "date": "2016-11-11T00:00:00",
        "supplier": "阳泉市上社二景煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤2#",
        "priceType": "基准价格",
        "salesPrice": 440.00,
        "priceEnum": 0
    }, {
        "id": 9535,
        "date": "2016-11-11T00:00:00",
        "supplier": "山西煤炭运销集团阳泉上社晋玉煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "混煤",
        "priceType": "基准价格",
        "salesPrice": 150.00,
        "priceEnum": 0
    }, {
        "id": 9536,
        "date": "2016-11-11T00:00:00",
        "supplier": "山西煤炭运销集团盂县恒泰常顺煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤（常顺）",
        "priceType": "基准价格",
        "salesPrice": 520.00,
        "priceEnum": 0
    }, {
        "id": 9537,
        "date": "2016-11-11T00:00:00",
        "supplier": "山西煤炭运销集团盂县恒泰常顺煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 520.00,
        "priceEnum": 0
    }, {
        "id": 9538,
        "date": "2016-11-11T00:00:00",
        "supplier": "山西煤炭运销集团盂县恒泰常顺煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "混煤",
        "priceType": "基准价格",
        "salesPrice": 200.00,
        "priceEnum": 0
    }, {
        "id": 9539,
        "date": "2016-11-11T00:00:00",
        "supplier": "山西煤炭运销集团盂县恒泰皇后煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 560.00,
        "priceEnum": 0
    }, {
        "id": 9540,
        "date": "2016-11-10T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤泥",
        "priceType": "基准价格",
        "salesPrice": 210.00,
        "priceEnum": 0
    }, {
        "id": 9541,
        "date": "2016-11-10T00:00:00",
        "supplier": "阳泉市上社煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤泥",
        "priceType": "基准价格",
        "salesPrice": 220.00,
        "priceEnum": 0
    }, {
        "id": 9542,
        "date": "2016-11-10T00:00:00",
        "supplier": "山西煤炭运销集团保安煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤泥",
        "priceType": "基准价格",
        "salesPrice": 260.00,
        "priceEnum": 0
    }, {
        "id": 9543,
        "date": "2016-11-08T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 560.00,
        "priceEnum": 0
    }, {
        "id": 9544,
        "date": "2016-11-08T00:00:00",
        "supplier": "阳泉市上社煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 570.00,
        "priceEnum": 0
    }, {
        "id": 9545,
        "date": "2016-11-08T00:00:00",
        "supplier": "阳泉市上社煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "末煤",
        "priceType": "基准价格",
        "salesPrice": 550.00,
        "priceEnum": 0
    }, {
        "id": 9546,
        "date": "2016-11-08T00:00:00",
        "supplier": "阳泉市上社二景煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 520.00,
        "priceEnum": 0
    }, {
        "id": 9547,
        "date": "2016-11-08T00:00:00",
        "supplier": "阳泉市上社二景煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤2#",
        "priceType": "基准价格",
        "salesPrice": 410.00,
        "priceEnum": 0
    }, {
        "id": 9548,
        "date": "2016-11-08T00:00:00",
        "supplier": "山西煤炭运销集团阳泉上社晋玉煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 460.00,
        "priceEnum": 0
    }, {
        "id": 9549,
        "date": "2016-11-08T00:00:00",
        "supplier": "山西煤炭运销集团阳泉二景和谐煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 450.00,
        "priceEnum": 0
    }, {
        "id": 9550,
        "date": "2016-11-08T00:00:00",
        "supplier": "山西煤炭运销集团保安煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 570.00,
        "priceEnum": 0
    }, {
        "id": 9551,
        "date": "2016-11-08T00:00:00",
        "supplier": "山西煤炭运销集团旧街煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 510.00,
        "priceEnum": 0
    }, {
        "id": 9552,
        "date": "2016-11-08T00:00:00",
        "supplier": "山西煤炭运销集团旧街煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "混煤",
        "priceType": "基准价格",
        "salesPrice": 400.00,
        "priceEnum": 0
    }, {
        "id": 9553,
        "date": "2016-11-08T00:00:00",
        "supplier": "山西煤炭运销集团鸿泰煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 630.00,
        "priceEnum": 0
    }, {
        "id": 9554,
        "date": "2016-11-05T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "二炭",
        "priceType": "基准价格",
        "salesPrice": 860.00,
        "priceEnum": 0
    }, {
        "id": 9555,
        "date": "2016-11-05T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "大块",
        "priceType": "基准价格",
        "salesPrice": 760.00,
        "priceEnum": 0
    }, {
        "id": 9556,
        "date": "2016-11-05T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "三炭",
        "priceType": "基准价格",
        "salesPrice": 800.00,
        "priceEnum": 0
    }, {
        "id": 9557,
        "date": "2016-11-05T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "筛末煤",
        "priceType": "基准价格",
        "salesPrice": 630.00,
        "priceEnum": 0
    }, {
        "id": 9558,
        "date": "2016-11-05T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "四炭",
        "priceType": "基准价格",
        "salesPrice": 740.00,
        "priceEnum": 0
    }, {
        "id": 9559,
        "date": "2016-11-05T00:00:00",
        "supplier": "阳泉市上社煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "混块",
        "priceType": "基准价格",
        "salesPrice": 730.00,
        "priceEnum": 0
    }, {
        "id": 9560,
        "date": "2016-11-05T00:00:00",
        "supplier": "山西煤炭运销集团保安煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "大块",
        "priceType": "基准价格",
        "salesPrice": 860.00,
        "priceEnum": 0
    }, {
        "id": 9561,
        "date": "2016-11-05T00:00:00",
        "supplier": "山西煤炭运销集团保安煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "小块",
        "priceType": "基准价格",
        "salesPrice": 760.00,
        "priceEnum": 0
    }, {
        "id": 9562,
        "date": "2016-11-05T00:00:00",
        "supplier": "山西煤炭运销集团保安煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "中块",
        "priceType": "基准价格",
        "salesPrice": 800.00,
        "priceEnum": 0
    }, {
        "id": 9563,
        "date": "2016-11-05T00:00:00",
        "supplier": "山西煤炭运销集团保安煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "筛末煤",
        "priceType": "基准价格",
        "salesPrice": 630.00,
        "priceEnum": 0
    }, {
        "id": 9564,
        "date": "2016-11-05T00:00:00",
        "supplier": "山西煤炭运销集团旧街煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "混煤",
        "priceType": "基准价格",
        "salesPrice": 370.00,
        "priceEnum": 0
    }, {
        "id": 9565,
        "date": "2016-11-05T00:00:00",
        "supplier": "山西煤炭运销集团鸿泰煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 610.00,
        "priceEnum": 0
    }, {
        "id": 9566,
        "date": "2016-11-05T00:00:00",
        "supplier": "山西煤炭运销集团鸿泰煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "混煤",
        "priceType": "基准价格",
        "salesPrice": 330.00,
        "priceEnum": 0
    }, {
        "id": 9567,
        "date": "2016-11-05T00:00:00",
        "supplier": "山西煤炭运销集团鸿泰煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "炭",
        "priceType": "基准价格",
        "salesPrice": 750.00,
        "priceEnum": 0
    }, {
        "id": 9568,
        "date": "2016-11-02T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 550.00,
        "priceEnum": 0
    }, {
        "id": 9569,
        "date": "2016-11-02T00:00:00",
        "supplier": "山西煤炭运销集团盂县恒泰常顺煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤（常顺）",
        "priceType": "基准价格",
        "salesPrice": 500.00,
        "priceEnum": 0
    }, {
        "id": 9570,
        "date": "2016-11-02T00:00:00",
        "supplier": "山西煤炭运销集团盂县恒泰皇后煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 540.00,
        "priceEnum": 0
    }, {
        "id": 9571,
        "date": "2016-11-02T00:00:00",
        "supplier": "山西煤炭运销集团保安煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "精煤",
        "priceType": "基准价格",
        "salesPrice": 480.00,
        "priceEnum": 0
    }, {
        "id": 9572,
        "date": "2016-11-01T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 540.00,
        "priceEnum": 0
    }, {
        "id": 9573,
        "date": "2016-11-01T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "二炭",
        "priceType": "基准价格",
        "salesPrice": 810.00,
        "priceEnum": 0
    }, {
        "id": 9574,
        "date": "2016-11-01T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "大块",
        "priceType": "基准价格",
        "salesPrice": 730.00,
        "priceEnum": 0
    }, {
        "id": 9575,
        "date": "2016-11-01T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤泥",
        "priceType": "基准价格",
        "salesPrice": 170.00,
        "priceEnum": 0
    }, {
        "id": 9576,
        "date": "2016-11-01T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "三炭",
        "priceType": "基准价格",
        "salesPrice": 750.00,
        "priceEnum": 0
    }, {
        "id": 9577,
        "date": "2016-11-01T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "筛末煤",
        "priceType": "基准价格",
        "salesPrice": 600.00,
        "priceEnum": 0
    }, {
        "id": 9578,
        "date": "2016-11-01T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "四炭",
        "priceType": "基准价格",
        "salesPrice": 690.00,
        "priceEnum": 0
    }, {
        "id": 9579,
        "date": "2016-11-01T00:00:00",
        "supplier": "阳泉市上社煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 560.00,
        "priceEnum": 0
    }, {
        "id": 9580,
        "date": "2016-11-01T00:00:00",
        "supplier": "阳泉市上社煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "混块",
        "priceType": "基准价格",
        "salesPrice": 690.00,
        "priceEnum": 0
    }, {
        "id": 9581,
        "date": "2016-11-01T00:00:00",
        "supplier": "阳泉市上社煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "末煤",
        "priceType": "基准价格",
        "salesPrice": 540.00,
        "priceEnum": 0
    }, {
        "id": 9582,
        "date": "2016-11-01T00:00:00",
        "supplier": "阳泉市上社二景煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 500.00,
        "priceEnum": 0
    }, {
        "id": 9583,
        "date": "2016-11-01T00:00:00",
        "supplier": "阳泉市上社二景煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤2#",
        "priceType": "基准价格",
        "salesPrice": 400.00,
        "priceEnum": 0
    }, {
        "id": 9584,
        "date": "2016-11-01T00:00:00",
        "supplier": "山西煤炭运销集团阳泉上社晋玉煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 450.00,
        "priceEnum": 0
    }, {
        "id": 9585,
        "date": "2016-11-01T00:00:00",
        "supplier": "山西煤炭运销集团阳泉二景和谐煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 430.00,
        "priceEnum": 0
    }, {
        "id": 9586,
        "date": "2016-11-01T00:00:00",
        "supplier": "山西煤炭运销集团盂县恒泰常顺煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤（常顺）",
        "priceType": "基准价格",
        "salesPrice": 480.00,
        "priceEnum": 0
    }, {
        "id": 9587,
        "date": "2016-11-01T00:00:00",
        "supplier": "山西煤炭运销集团盂县恒泰常顺煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 480.00,
        "priceEnum": 0
    }, {
        "id": 9588,
        "date": "2016-11-01T00:00:00",
        "supplier": "山西煤炭运销集团盂县恒泰皇后煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 520.00,
        "priceEnum": 0
    }, {
        "id": 9589,
        "date": "2016-11-01T00:00:00",
        "supplier": "山西煤炭运销集团保安煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "大块",
        "priceType": "基准价格",
        "salesPrice": 830.00,
        "priceEnum": 0
    }, {
        "id": 9590,
        "date": "2016-11-01T00:00:00",
        "supplier": "山西煤炭运销集团保安煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "小块",
        "priceType": "基准价格",
        "salesPrice": 710.00,
        "priceEnum": 0
    }, {
        "id": 9591,
        "date": "2016-11-01T00:00:00",
        "supplier": "山西煤炭运销集团保安煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "中块",
        "priceType": "基准价格",
        "salesPrice": 750.00,
        "priceEnum": 0
    }, {
        "id": 9592,
        "date": "2016-11-01T00:00:00",
        "supplier": "山西煤炭运销集团保安煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "筛末煤",
        "priceType": "基准价格",
        "salesPrice": 600.00,
        "priceEnum": 0
    }, {
        "id": 9593,
        "date": "2016-11-01T00:00:00",
        "supplier": "山西煤炭运销集团旧街煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 490.00,
        "priceEnum": 0
    }, {
        "id": 9594,
        "date": "2016-11-01T00:00:00",
        "supplier": "山西煤炭运销集团旧街煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "混煤",
        "priceType": "基准价格",
        "salesPrice": 340.00,
        "priceEnum": 0
    }, {
        "id": 9595,
        "date": "2016-11-01T00:00:00",
        "supplier": "山西煤炭运销集团旧街煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "炭",
        "priceType": "基准价格",
        "salesPrice": 660.00,
        "priceEnum": 0
    }, {
        "id": 9596,
        "date": "2016-10-30T00:00:00",
        "supplier": "山西煤炭运销集团保安煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 550.00,
        "priceEnum": 0
    }, {
        "id": 9597,
        "date": "2016-10-30T00:00:00",
        "supplier": "山西煤炭运销集团鸿泰煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 580.00,
        "priceEnum": 0
    }, {
        "id": 9598,
        "date": "2016-10-26T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 520.00,
        "priceEnum": 0
    }, {
        "id": 9599,
        "date": "2016-10-26T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "二炭",
        "priceType": "基准价格",
        "salesPrice": 800.00,
        "priceEnum": 0
    }, {
        "id": 9600,
        "date": "2016-10-26T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "大块",
        "priceType": "基准价格",
        "salesPrice": 720.00,
        "priceEnum": 0
    }, {
        "id": 9601,
        "date": "2016-10-26T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤泥",
        "priceType": "基准价格",
        "salesPrice": 170.00,
        "priceEnum": 0
    }, {
        "id": 9602,
        "date": "2016-10-26T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "三炭",
        "priceType": "基准价格",
        "salesPrice": 740.00,
        "priceEnum": 0
    }, {
        "id": 9603,
        "date": "2016-10-26T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "筛末煤",
        "priceType": "基准价格",
        "salesPrice": 580.00,
        "priceEnum": 0
    }, {
        "id": 9604,
        "date": "2016-10-26T00:00:00",
        "supplier": "阳泉市燕龛煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "四炭",
        "priceType": "基准价格",
        "salesPrice": 660.00,
        "priceEnum": 0
    }, {
        "id": 9605,
        "date": "2016-10-26T00:00:00",
        "supplier": "阳泉市上社煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 540.00,
        "priceEnum": 0
    }, {
        "id": 9606,
        "date": "2016-10-26T00:00:00",
        "supplier": "阳泉市上社煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "混块",
        "priceType": "基准价格",
        "salesPrice": 670.00,
        "priceEnum": 0
    }, {
        "id": 9607,
        "date": "2016-10-26T00:00:00",
        "supplier": "阳泉市上社煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤泥",
        "priceType": "基准价格",
        "salesPrice": 180.00,
        "priceEnum": 0
    }, {
        "id": 9608,
        "date": "2016-10-26T00:00:00",
        "supplier": "阳泉市上社二景煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 470.00,
        "priceEnum": 0
    }, {
        "id": 9609,
        "date": "2016-10-26T00:00:00",
        "supplier": "阳泉市上社二景煤炭有限责任公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤2#",
        "priceType": "基准价格",
        "salesPrice": 390.00,
        "priceEnum": 0
    }, {
        "id": 9610,
        "date": "2016-10-26T00:00:00",
        "supplier": "山西煤炭运销集团阳泉上社晋玉煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 430.00,
        "priceEnum": 0
    }, {
        "id": 9611,
        "date": "2016-10-26T00:00:00",
        "supplier": "山西煤炭运销集团保安煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤",
        "priceType": "基准价格",
        "salesPrice": 520.00,
        "priceEnum": 0
    }, {
        "id": 9612,
        "date": "2016-10-26T00:00:00",
        "supplier": "山西煤炭运销集团保安煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "大块",
        "priceType": "基准价格",
        "salesPrice": 810.00,
        "priceEnum": 0
    }, {
        "id": 9613,
        "date": "2016-10-26T00:00:00",
        "supplier": "山西煤炭运销集团保安煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "煤泥",
        "priceType": "基准价格",
        "salesPrice": 220.00,
        "priceEnum": 0
    }, {
        "id": 9614,
        "date": "2016-10-26T00:00:00",
        "supplier": "山西煤炭运销集团保安煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "小块",
        "priceType": "基准价格",
        "salesPrice": 690.00,
        "priceEnum": 0
    }, {
        "id": 9615,
        "date": "2016-10-26T00:00:00",
        "supplier": "山西煤炭运销集团保安煤业有限公司",
        "coalType": "贫瘦煤",
        "coalQuality": "中块",
        "priceType": "基准价格",
        "salesPrice": 730.00,
        "priceEnum": 0
    }];